/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.io.IOException;
import megapoly.Jugador;
import megapoly.Tablero;

/**
 *
 * @author Badal
 */
public class PantallaNuevaPartida extends javax.swing.JFrame {

  /**
   * Creates new form PantallaInicio
   */
  public PantallaNuevaPartida() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    BotonEmpezarPartida = new javax.swing.JButton();
    LabelCreacion = new javax.swing.JLabel();
    LabelJugador1 = new javax.swing.JLabel();
    LabelJugador2 = new javax.swing.JLabel();
    TextJugador1 = new javax.swing.JTextField();
    TextJugador2 = new javax.swing.JTextField();
    BotonAtras = new javax.swing.JButton();
    LabelMenu = new javax.swing.JLabel();
    Label = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    Menu = new javax.swing.JMenu();
    MenuNueva = new javax.swing.JMenuItem();
    MenuCargar = new javax.swing.JMenuItem();
    MenuSalir = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    BotonEmpezarPartida.setBackground(new java.awt.Color(102, 102, 102));
    BotonEmpezarPartida.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
    BotonEmpezarPartida.setForeground(new java.awt.Color(255, 255, 255));
    BotonEmpezarPartida.setText("Empezar partida");
    BotonEmpezarPartida.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BotonEmpezarPartidaActionPerformed(evt);
      }
    });
    jPanel1.add(BotonEmpezarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 290, 60));

    LabelCreacion.setFont(new java.awt.Font("Segoe UI Black", 1, 20)); // NOI18N
    LabelCreacion.setForeground(new java.awt.Color(255, 255, 255));
    LabelCreacion.setText("Creación de jugadores:");
    jPanel1.add(LabelCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

    LabelJugador1.setBackground(new java.awt.Color(255, 255, 255));
    LabelJugador1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
    LabelJugador1.setForeground(new java.awt.Color(255, 255, 255));
    LabelJugador1.setText("Jugador 2:");
    jPanel1.add(LabelJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

    LabelJugador2.setBackground(new java.awt.Color(255, 255, 255));
    LabelJugador2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
    LabelJugador2.setForeground(new java.awt.Color(255, 255, 255));
    LabelJugador2.setText("Jugador 1:");
    jPanel1.add(LabelJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

    TextJugador1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        TextJugador1ActionPerformed(evt);
      }
    });
    jPanel1.add(TextJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 240, 30));
    jPanel1.add(TextJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 240, 30));

    BotonAtras.setBackground(new java.awt.Color(102, 102, 102));
    BotonAtras.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
    BotonAtras.setForeground(new java.awt.Color(255, 255, 255));
    BotonAtras.setText("Atrás");
    BotonAtras.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BotonAtrasActionPerformed(evt);
      }
    });
    jPanel1.add(BotonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 290, 60));

    LabelMenu.setBackground(new java.awt.Color(255, 255, 255));
    LabelMenu.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
    LabelMenu.setForeground(new java.awt.Color(255, 255, 255));
    LabelMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    LabelMenu.setText("Menú");
    jPanel1.add(LabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 350, 70));

    Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PantallaInicio.png"))); // NOI18N
    jPanel1.add(Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

    Menu.setText("Archivo");

    MenuNueva.setText("Nueva partida");
    Menu.add(MenuNueva);

    MenuCargar.setText("Cargar partida");
    MenuCargar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        MenuCargarActionPerformed(evt);
      }
    });
    Menu.add(MenuCargar);

    MenuSalir.setText("Salir");
    MenuSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        MenuSalirActionPerformed(evt);
      }
    });
    Menu.add(MenuSalir);

    jMenuBar1.add(Menu);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void BotonEmpezarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEmpezarPartidaActionPerformed
    
    PantallaTablero pantallaTablero = new PantallaTablero((TextJugador1.getText()), (TextJugador2.getText()));
    pantallaTablero.setVisible(true);
    
    dispose();
    
                
  }//GEN-LAST:event_BotonEmpezarPartidaActionPerformed

  private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
                dispose(); // Cierra el JFrame
                System.exit(0);    
  }//GEN-LAST:event_MenuSalirActionPerformed

  private void BotonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasActionPerformed
    // TODO add your handling code here:
    PantallaInicio pantallaInicio = new PantallaInicio();
    pantallaInicio.setVisible(true);
    dispose();
  }//GEN-LAST:event_BotonAtrasActionPerformed

  private void TextJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextJugador1ActionPerformed
    // TODO add your handling code here:
    
  }//GEN-LAST:event_TextJugador1ActionPerformed

  private void MenuCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCargarActionPerformed
    // TODO add your handling code here:
    
    Jugador jugador1 = new Jugador();
    Jugador jugador2 = new Jugador();
    
    try {
      jugador1 = jugador1.leerDatos1("datosJugador1.dat");
    } catch (IOException ex) {
     
    } catch (ClassNotFoundException ex) {
    
    }
    try {
      jugador2 = jugador2.leerDatos1("datosJugador2.dat");
    } catch (IOException ex) {
     
    } catch (ClassNotFoundException ex) {
     
    }
    
    
   PantallaTablero pantallaTablero = new PantallaTablero(jugador1, jugador2);
   pantallaTablero.setVisible(true);
  }//GEN-LAST:event_MenuCargarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(PantallaNuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(PantallaNuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(PantallaNuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(PantallaNuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new PantallaNuevaPartida().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton BotonAtras;
  private javax.swing.JButton BotonEmpezarPartida;
  private javax.swing.JLabel Label;
  private javax.swing.JLabel LabelCreacion;
  private javax.swing.JLabel LabelJugador1;
  private javax.swing.JLabel LabelJugador2;
  private javax.swing.JLabel LabelMenu;
  private javax.swing.JMenu Menu;
  private javax.swing.JMenuItem MenuCargar;
  private javax.swing.JMenuItem MenuNueva;
  private javax.swing.JMenuItem MenuSalir;
  private javax.swing.JTextField TextJugador1;
  private javax.swing.JTextField TextJugador2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
