/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import megapoly.Jugador;

/**
 *
 * @author Badal
 */
public class PantallaInicio extends javax.swing.JFrame {

  /**
   * Creates new form PantallaInicio
   */
  public PantallaInicio() {
    initComponents();
  }
  
  public static PantallaTablero leerDatos(String ruta) throws IOException, ClassNotFoundException {

    FileInputStream fis = null;
    ObjectInputStream entrada = null;
    PantallaTablero juego = null;

    //Se leen las notas del fichero
    fis = new FileInputStream(ruta);
    entrada = new ObjectInputStream(fis);

    juego = (PantallaTablero) entrada.readObject();
    
    return juego;

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    BotonNueva = new javax.swing.JButton();
    BotonCargar = new javax.swing.JButton();
    BotonSalir = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    Menu = new javax.swing.JMenu();
    MenuNueva = new javax.swing.JMenuItem();
    MenuCargar = new javax.swing.JMenuItem();
    MenuSalir = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    BotonNueva.setBackground(new java.awt.Color(102, 102, 102));
    BotonNueva.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
    BotonNueva.setForeground(new java.awt.Color(255, 255, 255));
    BotonNueva.setText("Nueva partida");
    BotonNueva.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BotonNuevaActionPerformed(evt);
      }
    });
    jPanel1.add(BotonNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 290, 60));

    BotonCargar.setBackground(new java.awt.Color(102, 102, 102));
    BotonCargar.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
    BotonCargar.setForeground(new java.awt.Color(255, 255, 255));
    BotonCargar.setText("Cargar partida");
    BotonCargar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BotonCargarActionPerformed(evt);
      }
    });
    jPanel1.add(BotonCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 290, 60));

    BotonSalir.setBackground(new java.awt.Color(102, 102, 102));
    BotonSalir.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
    BotonSalir.setForeground(new java.awt.Color(255, 255, 255));
    BotonSalir.setText("Salir");
    BotonSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        BotonSalirActionPerformed(evt);
      }
    });
    jPanel1.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 290, 60));

    jLabel1.setBackground(new java.awt.Color(255, 255, 255));
    jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Menú");
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 350, 70));

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PantallaInicio.png"))); // NOI18N
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

    Menu.setText("Archivo");

    MenuNueva.setText("Nueva partida");
    MenuNueva.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        MenuNuevaActionPerformed(evt);
      }
    });
    Menu.add(MenuNueva);

    MenuCargar.setText("Cargar partida");
    MenuCargar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        MenuCargarActionPerformed(evt);
      }
    });
    Menu.add(MenuCargar);

    MenuSalir.setText("Salir");
    MenuSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        MenuSalirActionPerformed(evt);
      }
    });
    Menu.add(MenuSalir);

    jMenuBar1.add(Menu);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void BotonNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevaActionPerformed
    
    PantallaNuevaPartida pantallaNuevaPartida = new PantallaNuevaPartida();
    pantallaNuevaPartida.setVisible(true);
    
    dispose();
   
  }//GEN-LAST:event_BotonNuevaActionPerformed

  private void BotonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarActionPerformed
    // TODO add your handling code here:
    
    Jugador jugador1 = new Jugador();
    Jugador jugador2 = new Jugador();
    
    try {
      jugador1 = jugador1.leerDatos1("datosJugador1.dat");
    } catch (IOException ex) {
      Logger.getLogger(PantallaInicio.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
      Logger.getLogger(PantallaInicio.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
      jugador2 = jugador2.leerDatos1("datosJugador2.dat");
    } catch (IOException ex) {
      Logger.getLogger(PantallaInicio.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
      Logger.getLogger(PantallaInicio.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
   PantallaTablero pantallaTablero = new PantallaTablero(jugador1, jugador2);
   pantallaTablero.setVisible(true);
   
  
   
    
    
    
  }//GEN-LAST:event_BotonCargarActionPerformed

  private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
    
                dispose(); // Cierra el JFrame
                System.exit(0);
  }//GEN-LAST:event_BotonSalirActionPerformed

  private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
                dispose(); // Cierra el JFrame
                System.exit(0);    
  }//GEN-LAST:event_MenuSalirActionPerformed

  private void MenuNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNuevaActionPerformed
    PantallaNuevaPartida pantallaNuevaPartida = new PantallaNuevaPartida();
    pantallaNuevaPartida.setVisible(true);
  }//GEN-LAST:event_MenuNuevaActionPerformed

  private void MenuCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCargarActionPerformed
    // TODO add your handling code here:
    Jugador jugador1 = new Jugador();
    Jugador jugador2 = new Jugador();
    
    try {
      jugador1 = jugador1.leerDatos1("datosJugador1.dat");
    } catch (IOException ex) {
      Logger.getLogger(PantallaInicio.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
      Logger.getLogger(PantallaInicio.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
      jugador2 = jugador2.leerDatos1("datosJugador2.dat");
    } catch (IOException ex) {
      Logger.getLogger(PantallaInicio.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
      Logger.getLogger(PantallaInicio.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    
   PantallaTablero pantallaTablero = new PantallaTablero(jugador1, jugador2);
   pantallaTablero.setVisible(true);
  }//GEN-LAST:event_MenuCargarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new PantallaInicio().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton BotonCargar;
  private javax.swing.JButton BotonNueva;
  private javax.swing.JButton BotonSalir;
  private javax.swing.JMenu Menu;
  private javax.swing.JMenuItem MenuCargar;
  private javax.swing.JMenuItem MenuNueva;
  private javax.swing.JMenuItem MenuSalir;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
